### PR TITLE
Complete channels that were cleaning up when we restart

### PR DESCRIPTION
**Pull request by aarshkshah1992**
For filecoin-project/lotus#3417.

### CODE REVIEW

**Review by hannahhoward — CHANGES_REQUESTED** [review]
We should probably either write an integration test or at minimum a unit test for RestartDataTransferChannel that verifies this works.

**Comment by hannahhoward** [comment]
(if you want to merge as is and address comment seperately let me know and I'll remove the request changes)

**Comment by hannahhoward** [comment]
I guess in fairness and integration test would be hard so maybe just a unit test

**Comment by aarshkshah1992** [comment]
@hannahhoward I am not sure how to write a unit test for thus considering that as soon as a channel transitions to one of the penultimate states(Completing, Cancelling etc), the `CleanupChannel` handler for those states takes the channel to completion in an async way.

How do I get a channel that remains stuck rather than completing on those states so we can complete them on restart (for a NON-FLAKY test) ?

**Comment by hannahhoward** [comment]
Fair enough, let's not worry bout it.

**Review by hannahhoward — APPROVED** [review]

**Pull request merged**
