### PR TITLE
Emit events with received cids

### PR DESCRIPTION
**Pull request by aarshkshah1992**
For https://github.com/filecoin-project/lotus/issues/3417.

@hannahhoward This is step 1 which emits the receieved cids along with the channel event and state.

This PR is against a long running feature branch.

### CODE REVIEW

**Review by hannahhoward — APPROVED** [review]
LGTM. Be careful when you filter up to Storage/Retrieval that they may be relying on the old Progress event, so just keep an eye out there.

**Review by hannahhoward — CHANGES_REQUESTED** [review]
Be careful when you filter up to Storage/Retrieval that they may be relying on the old Progress event, so just keep an eye out there.

Follow-up: I do not think we should record sentCIDs. We may be transferring pieces with 1000000s of CIDs and unless we have a direct use for them, putting all those on disk for every data transfer feels very expensive.

**Review by hannahhoward — APPROVED** [review]

**Comment by hannahhoward** [comment]
Not blocking on changes cause it's just a feature branch and don't want to block you, but see feedback about sentCids -- there's a cost here in disk space if they aren't directly used.

**Comment by aarshkshah1992** [comment]
@hannahhoward Not recording sent cids anymore.

**Pull request merged**
