### PR TITLE
Update go-graphsync v0.8.0

### PR DESCRIPTION
**Pull request by hannahhoward**
# Goals

Good news: The latest version of go-graphync and go-ipld-prime contains an important optimization to remove a bunch of unneccesary hashing when reading from local blockstores, which should cut down significantly on CPU usage
Bad news: The latest versions of these libraries contain a some important, but very breaking changes to syntax.
Good news: I'm updating them all the way to Lotus! And also, in most cases, from the point of view of the consuming libraries, they're simplifications.

# Implementation

- Update to go-graphsync v0.8.0 with go-ipld-prime linksystem branch & trusted store.
- Fix syntax changes which are mostly to:
   - dagcbor Encode / Decode function name
   - use of linksystem over loader + storer.
   
# Background

- More about the LinkSystem: https://github.com/ipld/go-ipld-prime/pull/143
- Trusted store branch: https://github.com/ipld/go-ipld-prime/pull/149
- PR to merge LinkSystem into go-graphsync: https://github.com/ipfs/go-graphsync/pull/161

### CODE REVIEW

**Comment by tchardin** [comment]
@dirkmc what is the timing for this? Unfortunately we cannot use the latest go-data-transfer release because it relies on changes made to an older version of graphsync that is incompatible with ipld-prime v0.7.0 used in our project. Cannot run it from the commit either since there are breaking changes with go-fil-markets. So sadly we can't benefit from the changes you made until this gets in.

**Comment by dirkmc** [comment]
@tchardin we've been doing some performance testing of graphsync v0.8.0. You can follow the progress at https://github.com/filecoin-project/go-data-transfer/issues/166

It seems like there may need to be further optimizations made before a newer version of graphsync can be integrated into go-data-transfer.

I'd suggest you align your code with the [latest release of go-data-transfer v1.7.0](https://github.com/filecoin-project/go-data-transfer/releases/tag/v1.7.0) which uses [graphsync v0.6.4](https://github.com/filecoin-project/go-data-transfer/blob/v1.7.0/go.mod#L16)

**Comment by tchardin** [comment]
Gotcha, thanks @dirkmc. So you confirm it would be faster to downgrade our project to ipld-prime v0.5.1 instead of waiting for this to get in?

**Comment by dirkmc** [comment]
I think that's probably your best bet 👍

**Pull request closed without merging**
